openapi: 3.1.0
info:
  title: Burgerservicenummer
  description: |
    Definitie voor burgerservicenummer, een identificatienummer van een persoon geregistreerd in de BRP
  version: 1.0.0
  contact: {}
components:
  schemas:
    Burgerservicenummer:
      $ref: '../tekst/tekst-9-cijfers-v1.yaml#/components/schemas/Cijfers'
      example: "555555021"
