openapi: 3.1.0
info:
  title: Datum
  description: |
    Definitie voor een datum conform LO BRP
  version: 1.0.0
  contact: {}
components:
  schemas:
    GbaDatum:
      $ref: '../tekst/tekst-8-cijfers-v1.yaml#/components/schemas/Cijfers'
      example: "20180700"
