openapi: 3.1.0
info:
  title: geboorte
  version: 1.0.0
components:
  schemas:
    GbaGeboorteBeperkt:
      type: object
      properties:
        datum:
          $ref: 'datum-v1.yaml#/components/schemas/GbaDatum'
    GbaGeboorte:
      allOf:
        - $ref: '#/components/schemas/GbaGeboorteBeperkt'
        - type: object
          properties:
            land:
              $ref: 'waardetabel-v1.yaml#/components/schemas/Waardetabel'
            plaats:
              $ref: 'waardetabel-v1.yaml#/components/schemas/Waardetabel'
