openapi: 3.1.0
info:
  title: Geheim
  version: 1.0.0
  contact: {}
components:
  schemas:
    GbaGeheimhoudingPersoonsgegevens:
      description: |
        Gegevens over het mogen verstrekken van persoonsgegevens aan derden / maatschappelijke instellingen.
      type: integer
      minimum: 0
      maximum: 7
