openapi: 3.1.0
info: 
  title: immigratie
  version: 1.0.0
components: 
  schemas:
    ImmigratieBasis:
      type: object
      properties:
        landVanwaarIngeschreven:
          description: |
            het land waar de persoon woonde voor (her)vestiging in Nederland.
          $ref: 'waardetabel-v1.yaml#/components/schemas/Waardetabel'
    GbaImmigratie:
      allOf: 
        - $ref: '#/components/schemas/ImmigratieBasis'
        - type: object
          properties:
            datumVestigingInNederland:
              $ref: 'datum-v1.yaml#/components/schemas/GbaDatum'
