openapi: 3.1.0
info:
  title: InOnderzoek
  version: 1.0.0
components:
  schemas:
    GbaInOnderzoek:
      type: object
      required:
        - aanduidingGegevensInOnderzoek
        - datumIngangOnderzoek
      properties:
        aanduidingGegevensInOnderzoek:
          type: string
          pattern: ^[0-9]{6}$
        datumIngangOnderzoek:
          $ref: 'datum-v1.yaml#/components/schemas/GbaDatum'
