openapi: 3.1.0
info:
  title: InOnderzoek
  version: 1.0.0
  contact: {}
components:
  schemas:
    GbaInOnderzoek:
      type: object
      required:
        - aanduidingGegevensInOnderzoek
        - datumIngangOnderzoek
      properties:
        aanduidingGegevensInOnderzoek:
          $ref: '../tekst/tekst-6-cijfers-v1.yaml#/components/schemas/Cijfers'
        datumIngangOnderzoek:
          $ref: 'datum-v1.yaml#/components/schemas/GbaDatum'
