openapi: 3.1.0
info:
  title: OpschortingBijhouding
  version: 1.0.0
  contact: {}
components:
  schemas:
    OpschortingBijhoudingBasis:
      type: object
      description: |
        Gegevens over het (gedeeltelijk) stoppen van de bijhouding van de persoonsgegevens
      properties:
        reden:
          description: Omschrijving reden opschorting bijhouding
          $ref: 'waardetabel-v1.yaml#/components/schemas/Waardetabel'
    OpschortingBijhouding:
      allOf:
        - $ref: '#/components/schemas/OpschortingBijhoudingBasis'
        - type: object
          properties:
            datum:
              description: Datum waarop de bijhouding is gestaakt
              $ref: 'datum-v1.yaml#/components/schemas/AbstractDatum'
