openapi: 3.1.0
info:
  title: OpschortingBijhouding (GBA)
  version: 1.0.0
  contact: {}
components:
  schemas:
    GbaOpschortingBijhouding:
      allOf:
        - $ref: 'opschorting-bijhouding-v1.yaml#/components/schemas/OpschortingBijhoudingBasis'
        - type: object
          properties:
            datum:
              description: Datum waarop de bijhouding is gestaakt
              $ref: 'datum-gba-v1.yaml#/components/schemas/GbaDatum'
