openapi: 3.1.0
info: 
  title: ouder
  version: 1.0.0
components: 
  schemas:
    OuderAanduiding:
      type: string
      pattern: ^[1|2]$
      example: '1'
    OuderBasis:
      type: object
      properties: 
        burgerservicenummer:
          $ref: 'identificatienummers/burgerservicenummer-v1.yaml#/components/schemas/Burgerservicenummer'
        geslacht:
          description: |
            wordt gevuld met waarden voor 'Geslacht' in 'tabelwaarden.csv'.
          $ref: 'waardetabel-v1.yaml#/components/schemas/Waardetabel'
        ouderAanduiding:
          $ref: '#/components/schemas/OuderAanduiding'
    GbaOuder:
      allOf: 
        - $ref: '#/components/schemas/OuderBasis'
        - type: object
          properties:
            datumIngangFamilierechtelijkeBetrekking:
              description: |
                De datum waarop de familierechtelijke betrekking is ontstaan.
              $ref: 'datum-v1.yaml#/components/schemas/GbaDatum'
            naam:
              $ref: 'naam/naam-basis-v1.yaml#/components/schemas/NaamBasis'
            geboorte:
              $ref: 'geboorte/geboorte-v1.yaml#/components/schemas/Geboorte'
            inOnderzoek:
              $ref: 'in-onderzoek-v1.yaml#/components/schemas/GbaInOnderzoek'
