openapi: 3.1.0
info: 
  title: verblijfstitel
  version: 1.0.0
components: 
  schemas:
    VerblijfstitelBasis:
      description: |
        Gegevens over de verblijfsrechtelijke status van de persoon.
      type: object
      properties:
        aanduiding:
          description: |
            Verblijfstiteltabel die aangeeft over welke verblijfsrechtelijke status de persoon beschikt. Wordt gevuld met waarden uit de landelijke tabel 'Verblijfstitel'.
          $ref: 'waardetabel-v1.yaml#/components/schemas/Waardetabel'
    GbaVerblijfstitel:
      allOf: 
        - $ref: '#/components/schemas/VerblijfstitelBasis'
        - type: object
          properties:
            datumEinde:
              description: |
                Datum waarop de geldigheid van de gegevens over de verblijfstitel is beëindigd.
              $ref: 'datum-v1.yaml#/components/schemas/GbaDatum'
            datumIngang:
              description: |
                Datum waarop de gegevens over de verblijfstitel geldig zijn geworden.
              $ref: 'datum-v1.yaml#/components/schemas/GbaDatum'
            inOnderzoek:
              $ref: 'in-onderzoek-v1.yaml#/components/schemas/GbaInOnderzoek'
