openapi: 3.1.0
info:
  title: Verblijfplaats
  version: 1.0.0
  contact: {}
components:
  schemas:
    AbstractVerblijfplaats:
      type: object
      description: |
        Gegevens over het verblijf of de woonlocatie van een persoon.
      required:
        - type
      properties:
        type:
          type: string
      discriminator:
        propertyName: type
        mapping:
          Adres: 'verblijfplaats-adres-v1.yaml#/components/schemas/Adres'
          Locatie: 'verblijfplaats-locatie-v1.yaml#/components/schemas/Locatie'
          VerblijfplaatsBuitenland: 'verblijfplaats-buitenland-v1.yaml#/components/schemas/VerblijfplaatsBuitenland'
          VerblijfplaatsOnbekend: 'verblijfplaats-onbekend-v1.yaml#/components/schemas/VerblijfplaatsOnbekend'
