openapi: 3.1.0
info:
  title: AdresVoorkomen
  version: 1.0.0
  contact: {}
components:
  schemas:
    AdresVoorkomen:
      description: |
        Gegevens over het adres voorkomen van een persoon.
        * **gemeenteVanInschrijving** - wordt gevuld met waarden uit de landelijke tabel 'Gemeenten'.
        * **functieAdres** - wordt gevuld met waarden voor 'Functie_Adres' in 'tabelwaarden.csv'.
        * **aanduidingBijHuisnummer** - wordt gevuld met waarden voor 'Aanduiding_Bij_Huisnummer' in 'tabelwaarden.csv'.
        * **datumVan** : de datum van aangifte of ambtshalve melding van verblijf en adres.
        * **datumIngangGeldigheid** : datum waarop de gegevens over de verblijfplaats geldig zijn geworden.
      allOf:
        - $ref : 'verblijfplaats-voorkomen-v1.yaml#/components/schemas/AbstractVerblijfplaatsVoorkomen'
        - type: object
          properties:
            verblijfadres:
              $ref: 'verblijfplaats-adres-v1.yaml#/components/schemas/VerblijfadresBinnenland'
            functieAdres:
              $ref: 'waardetabel-v1.yaml#/components/schemas/Waardetabel'
            adresseerbaarObjectIdentificatie:
              $ref: 'verblijfplaats-adres-v1.yaml#/components/schemas/AdresseerbaarObjectIdentificatie'
            nummeraanduidingIdentificatie:
              $ref: 'verblijfplaats-adres-v1.yaml#/components/schemas/NummeraanduidingIdentificatie'
            gemeenteVanInschrijving:
              $ref: 'waardetabel-v1.yaml#/components/schemas/Waardetabel'
            datumVan:
              $ref: 'datum-v1.yaml#/components/schemas/AbstractDatum'
            datumTot:
              $ref: 'datum-v1.yaml#/components/schemas/AbstractDatum'
            indicatieVastgesteldVerblijftNietOpAdres:
              $ref: 'verblijfplaats-adres-v1.yaml#/components/schemas/IndicatieVastgesteldVerblijftNietOpAdres'
            inOnderzoek:
              $ref: '#/components/schemas/AdresVoorkomenInOnderzoek'
    AdresVoorkomenInOnderzoek:
      allOf:
        - $ref: 'in-onderzoek-v1.yaml#/components/schemas/InOnderzoek'
        - type: object
          properties:
            type:
              type: boolean
            gemeenteVanInschrijving:
              type: boolean
            datumVan:
              type: boolean
            datumTot:
              type: boolean
            nummeraanduidingIdentificatie:
              type: boolean
            adresseerbaarObjectIdentificatie:
              type: boolean
            functieAdres:
              type: boolean
