openapi: 3.1.0
info:
  title: Locatie
  version: 1.0.0
  contact: {}
components:
  schemas:
    Locatiebeschrijving:
      type: string
      maxLength: 35
      description: |
        Omschrijving van de ligging van een verblijfsobject, standplaats of ligplaats.
      example: "Naast de derde brug"
    VerblijfadresLocatie:
      type: object
      properties:
        locatiebeschrijving:
          $ref: '#/components/schemas/Locatiebeschrijving'
        inOnderzoek:
          $ref: "#/components/schemas/VerblijfadresLocatieInOnderzoek"
    VerblijfadresLocatieInOnderzoek:
      allOf:
        - $ref: 'in-onderzoek-v1.yaml#/components/schemas/InOnderzoek'
        - type: object
          properties:
            locatiebeschrijving:
              type: boolean
    Locatie:
      description: |
        * **gemeenteVanInschrijving** - wordt gevuld met waarden uit de landelijke tabel 'Gemeenten'.
        * **functieAdres** - wordt gevuld met waarden voor 'Functie_Adres' in 'tabelwaarden.csv'.
        * **landVanWaarIngeschreven** : het land waar de persoon woonde voor (her)vestiging in Nederland. Wordt gevuld met waarden uit de landelijke tabel 'Landen'.
      allOf:
        - $ref: 'verblijfplaats-v1.yaml#/components/schemas/AbstractVerblijfplaats'
        - type: object
          properties:
            datumVan:
              $ref: 'datum-v1.yaml#/components/schemas/AbstractDatum'
            functieAdres:
              $ref: 'waardetabel-v1.yaml#/components/schemas/Waardetabel'
            verblijfadres:
              $ref: "#/components/schemas/VerblijfadresLocatie"
            datumIngangGeldigheid:
              $ref: 'datum-v1.yaml#/components/schemas/AbstractDatum'
            indicatieVastgesteldVerblijftNietOpAdres:
              $ref: 'verblijfplaats-adres-v1.yaml#/components/schemas/IndicatieVastgesteldVerblijftNietOpAdres'
            inOnderzoek:
              $ref: '#/components/schemas/LocatieInOnderzoek'
    LocatieInOnderzoek:
      allOf:
        - $ref: 'in-onderzoek-v1.yaml#/components/schemas/InOnderzoek'
        - type: object
          properties:
            type:
              type: boolean
            datumVan:
              type: boolean
            functieAdres:
              type: boolean
            datumIngangGeldigheid:
              type: boolean
