openapi: 3.1.0
info:
  title: VerblijfplaatsOnbekendVookomen
  version: 1.0.0
  contact: {}
components:
  schemas:
    VerblijfplaatsOnbekendVoorkomen:
      allOf:
        - $ref: 'verblijfplaats-voorkomen-v1.yaml#/components/schemas/AbstractVerblijfplaatsVoorkomen'
        - type: object
          properties:
            datumVan:
              $ref: 'datum-v1.yaml#/components/schemas/AbstractDatum'
            datumTot:
              $ref: 'datum-v1.yaml#/components/schemas/AbstractDatum'
            inOnderzoek:
              $ref: '#/components/schemas/VerblijfplaatsOnbekendVoorkomenInOnderzoek'
            rni:
              $ref: 'rni-v1.yaml#/components/schemas/RniDeelnemer'
    VerblijfplaatsOnbekendVoorkomenInOnderzoek:
      allOf:
        - $ref: 'in-onderzoek-v1.yaml#/components/schemas/InOnderzoek'
        - type: object
          properties:
            type:
              type: boolean
            datumVan:
              type: boolean
            datumTot:
              type: boolean
