openapi: 3.1.0
info:
  title: Verificatie
  version: 1.0.0
components:
  schemas:
    VerificatieBasis:
      type: object
      properties:
        omschrijving:
          type: string
          description: |
            Omschrijving van de verificatie van de rni-gegevens
          pattern: ^[a-zA-Z0-9À-ž \.\-\']{1,50}$
    GbaVerificatie:
      allOf: 
        - $ref: '#/components/schemas/VerificatieBasis'
        - type: object
          properties:
            datum:
              $ref: 'datum-v1.yaml#/components/schemas/GbaDatum'
