openapi: 3.1.0
info:
  title: gezagsrelatie type definitie
  version: 2.0.0
paths: {}
components:
  schemas:
    AbstractGezagsrelatie:
      type: object
      required:
        - type
        - minderjarige
      properties:
        type:
          type: string
        minderjarige:
          $ref: 'minderjarige-v1.yaml#/components/schemas/Minderjarige'
      discriminator:
        propertyName: type
        mapping:
          TweehoofdigOuderlijkGezag: '#/components/schemas/TweehoofdigOuderlijkGezag'
          EenhoofdigOuderlijkGezag: '#/components/schemas/EenhoofdigOuderlijkGezag'
          GezamenlijkGezag: '#/components/schemas/GezamenlijkGezag'
          Voogdij: '#/components/schemas/Voogdij'
          TijdelijkGeenGezag: '#/components/schemas/TijdelijkGeenGezag'
          GezagNietTeBepalen: '#/components/schemas/GezagNietTeBepalen'
      example:
        type: 'TweehoofdigOuderlijkGezag'
        ouders:
          - burgerservicenummer: '999998870'
          - burgerservicenummer: '999998882'
        minderjarige:
          burgerservicenummer: '999998894'

    TweehoofdigOuderlijkGezag:
      description: 'De naam van dit type is onjuist. De juiste term is "gezamenlijk ouderlijk gezag", en moet worden gebruikt in de communicatie met de eindgebruiker. In de eerst volgende major versie zal het type worden aangepast.'
      allOf:
        - $ref: '#/components/schemas/AbstractGezagsrelatie'
        - type: object
          properties:
            ouders:
              type: array
              items:
                $ref: 'gezagouder-v1.yaml#/components/schemas/GezagOuder'
              minItems: 2
              maxItems: 2

    EenhoofdigOuderlijkGezag:
      allOf:
        - $ref: '#/components/schemas/AbstractGezagsrelatie'
        - type: object
          properties:
            ouder:
              $ref: 'gezagouder-v1.yaml#/components/schemas/GezagOuder'

    GezamenlijkGezag:
      allOf:
        - $ref: '#/components/schemas/AbstractGezagsrelatie'
        - type: object
          properties:
            ouder:
              $ref: 'gezagouder-v1.yaml#/components/schemas/GezagOuder'
            derde:
              $ref: 'meerderjarige-v1.yaml#/components/schemas/Meerderjarige'

    Voogdij:
      allOf:
        - $ref: '#/components/schemas/AbstractGezagsrelatie'
        - type: object
          properties:
            derden:
              type: array
              items:
                $ref: 'meerderjarige-v1.yaml#/components/schemas/Meerderjarige'
              minItems: 0
              maxItems: 2

    TijdelijkGeenGezag:
      allOf:
        - $ref: '#/components/schemas/AbstractGezagsrelatie'
        - type: object
          properties:
            toelichting:
              $ref: 'toelichting-v1.yaml#/components/schemas/Toelichting'

    GezagNietTeBepalen:
      allOf:
        - $ref: '#/components/schemas/AbstractGezagsrelatie'
        - type: object
          properties:
            toelichting:
              $ref: 'toelichting-v1.yaml#/components/schemas/Toelichting'
