openapi: 3.1.0
info: 
  title: datum type
  description: datum conform ISO-8601 te gebruiken als bijv. peildatum, datumVan en datumTot
  version: 1.0.0
components: 
  schemas:
    Datum:
      type: string
      format: date
      example: 1964-09-24
