openapi: 3.1.0
info:
  title: leeftijd
  version: 1.0.0
components:
  schemas:
    Leeftijd:
      type: integer
      description: |
        Leeftijd in jaren op het moment van bevragen.
      example: 34
      minimum: 0
      maximum: 150
