openapi: 3.1.0
info: 
  title: partner
  version: 1.0.0
components: 
  schemas:
    Partner:
      allOf: 
        - $ref: '../brp/partner-v1.yaml#/components/schemas/PartnerBasis'
        - type: object
          properties:
            datumIngangFamilierechtelijkeBetrekking:
              description: |
                De datum waarop de familierechtelijke betrekking is ontstaan.
              $ref: 'datum-polymorf-v1.yaml#/components/schemas/AbstractDatum'
            naam:
              $ref: 'naam/naam-basis-v1.yaml#/components/schemas/NaamGerelateerde'
            geboorte:
              $ref: 'geboorte-v1.yaml#/components/schemas/Geboorte'
            aangaanHuwelijkPartnerschap:
              $ref: '#/components/schemas/AangaanHuwelijkPartnerschap'
            ontbindingHuwelijkPartnerschap:
              $ref: "#/components/schemas/OntbindingHuwelijkPartnerschap"
            inOnderzoek:
              $ref: '#/components/schemas/PartnerInOnderzoek'
    PartnerInOnderzoek:
      description: |
        Geeft aan welke gegevens over het huwelijk of het partnerschap in onderzoek zijn.
      allOf:
        - $ref: 'in-onderzoek-v1.yaml#/components/schemas/InOnderzoek'
        - type: object
          properties:
            burgerservicenummer:
              type: boolean
            geslacht:
              type: boolean
            soortVerbintenis:
              type: boolean
    AangaanHuwelijkPartnerschap:
      allOf: 
        - $ref: '../brp/partner-v1.yaml#/components/schemas/AangaanHuwelijkPartnerschapBasis'
        - type: object
          properties:
            datum:
              description: |
                De datum waarop het huwelijk is voltrokken of het partnerschap is aangegaan.
              $ref: 'datum-polymorf-v1.yaml#/components/schemas/AbstractDatum'
            inOnderzoek:
              $ref: '#/components/schemas/AangaanHuwelijkPartnerschapInOnderzoek'
    AangaanHuwelijkPartnerschapInOnderzoek:
      description: |
        Geeft aan welke gegevens over het voltrekken van het huwelijk of aangaan van het partnerschap in onderzoek zijn.
      allOf:
        - $ref: 'in-onderzoek-v1.yaml#/components/schemas/InOnderzoek'
        - type: object
          properties:
            datum:
              type: boolean
            land:
              type: boolean
            plaats:
              type: boolean
    OntbindingHuwelijkPartnerschap:
      type: object
      properties:
        datum:
          $ref: 'datum-polymorf-v1.yaml#/components/schemas/AbstractDatum'
        inOnderzoek:
          $ref: '#/components/schemas/OntbindingHuwelijkPartnerschapInOnderzoek'
    OntbindingHuwelijkPartnerschapInOnderzoek:
      description: |
        Geeft aan welke gegevens over het onbinden van het huwelijk of aangaan van het partnerschap in onderzoek zijn.
      allOf:
        - $ref: 'in-onderzoek-v1.yaml#/components/schemas/InOnderzoek'
        - type: object
          properties:
            datum:
              type: boolean
