openapi: 3.1.0
info:
  title: Periode
  version: 1.0.0
  contact: {}
components: 
  schemas:
    Periode:
      type: object
      properties:
        datumVan:
          $ref: 'datum-v1.yaml#/components/schemas/Datum'
          example: 2020-01-01
        datumTot:
          $ref: 'datum-v1.yaml#/components/schemas/Datum'
          example: 2021-01-01
