openapi: 3.1.0
info:
  title: Verificatie
  version: 1.0.0
components:
  schemas:
    Verificatie:
      allOf: 
        - $ref: '../brp/verificatie-v1.yaml#/components/schemas/VerificatieBasis'
        - type: object
          properties:
            datum:
              $ref: 'datum-polymorf-v1.yaml#/components/schemas/AbstractDatum'
