openapi: 3.1.0
info:
  title: derde type definitie
  version: 2.0.0
paths: {}
components:
  schemas:
    AbstractDerde:
      type: object
      required:
        - type
      properties:
        type:
          type: string
      discriminator:
        propertyName: type
        mapping:
          Derde: '#/components/schemas/Derde'
          OnbekendeDerde: '#/components/schemas/OnbekendeDerde'
            
    Derde:
      allOf:
        - $ref: '#/components/schemas/AbstractDerde'
        - type: object
          properties:
            burgerservicenummer:
              $ref: '../../brp/identificatienummers/burgerservicenummer-v1.yaml#/components/schemas/Burgerservicenummer'
            naam:
              $ref: '../naam/volledige-naam-v1.yaml#/components/schemas/NaamVolledigeNaam'

    OnbekendeDerde:
      allOf:
        - $ref: '#/components/schemas/AbstractDerde'
