openapi: 3.1.0
info:
  title: minderjarige
  version: 1.0.0
  contact: {}
components:
  schemas:
    Minderjarige:
      type: object
      properties:
        burgerservicenummer:
          $ref: '../../brp/identificatienummers/burgerservicenummer-v1.yaml#/components/schemas/Burgerservicenummer'
      required: 
        - burgerservicenummer
