openapi: 3.1.0
info: 
  title: Inschrijven Persoon Response
  version: 1.0.0
components:
  schemas:
    InschrijvenPersoonResponse:
      type: object
      properties:
        burgerservicenummer:
          $ref: ../brp/identificatienummers/burgerservicenummer-v1.yaml#/components/schemas/Burgerservicenummer
