openapi: 3.1.0
info:
  title: voornamen
  version: 1.0.0
components:
  schemas:
    description: |
      De verzameling namen voor de geslachtsnaam, gescheiden door spaties.
    Voornamen:
      type: string
      pattern: ^[a-zA-Z0-9À-ž \.\-\']{1,200}$
      maxLength: 200
