openapi: 3.1.0
info:
  title: Reisdocument houder (BRP variant)
  version: 1.0.0
components:
  schemas:
    ReisdocumenthouderBasis:
      type: object
      properties:
        burgerservicenummer:
          $ref: '../burgerservicenummer-v1.yaml#/components/schemas/Burgerservicenummer'
    GbaReisdocumenthouder:
      required: 
        - gemeenteVanInschrijving
      allOf:
        - $ref: '#/components/schemas/ReisdocumenthouderBasis'
        - type: object
          properties:
            geheimhoudingPersoonsgegevens:
              $ref: '../geheim-v1.yaml#/components/schemas/GbaGeheimhoudingPersoonsgegevens'
            opschortingBijhouding:
              $ref: '../opschorting-bijhouding-v1.yaml#/components/schemas/GbaOpschortingBijhouding'
            gemeenteVanInschrijving:
              description: wordt gebruikt om de afnemer te autoriseren voor het bevragen van het reisdocument
              $ref: '../waardetabel-v1.yaml#/components/schemas/Waardetabel'
            inOnderzoek:
              $ref: '../in-onderzoek-v1.yaml#/components/schemas/GbaInOnderzoek'
