openapi: 3.1.0
info:
  title: Reisdocument Inhouding of Vermissing (BRP variant)
  version: 1.0.0
components:
  schemas:
    InhoudingOfVermissingBasis:
      type: object
      properties:
        aanduiding:
          $ref: '../waardetabel-v1.yaml#/components/schemas/Waardetabel'
    GbaInhoudingOfVermissing:
      allOf: 
        - $ref: '#/components/schemas/InhoudingOfVermissingBasis'
        - type: object
          properties:
            datum:
              $ref: '../datum-v1.yaml#/components/schemas/GbaDatum'
