openapi: 3.1.0
info:
  title: Reisdocument (BRP variant)
  version: 1.0.0
components:
  schemas:
    ReisdocumentBasis:
      type: object
      properties:
        reisdocumentnummer:
          $ref: 'reisdocumentnummer-v1.yaml#/components/schemas/Reisdocumentnummer'
        soort:
          $ref: '../waardetabel-v1.yaml#/components/schemas/Waardetabel'
    GbaReisdocument:
      allOf: 
        - $ref: '#/components/schemas/ReisdocumentBasis'
        - type: object
          properties:
            datumEindeGeldigheid:
              $ref: '../datum-v1.yaml#/components/schemas/GbaDatum'
            inhoudingOfVermissing:
              $ref: 'inhouding-of-vermissing-v1.yaml#/components/schemas/GbaInhoudingOfVermissing'
            houder:
              $ref: 'houder-v1.yaml#/components/schemas/GbaReisdocumenthouder'
            inOnderzoek:
              $ref: '../in-onderzoek-v1.yaml#/components/schemas/GbaInOnderzoek'
