openapi: 3.1.0
info:
  title: naam
  version: 1.0.0
  contact: {}
components:
  schemas:
    NaamPersoon:
      description: |
        Gegevens over de naam van de persoon.
        * **aanduidingNaamgebruik** - wordt gevuld met waarden voor 'Naamgebruik' in 'tabelwaarden.csv'.
      allOf:
        - $ref: 'naam-beperkt-v1.yaml#/components/schemas/NaamPersoonBeperkt'
        - properties:
            aanduidingNaamgebruik:
              $ref: '../../brp/waardetabel-v1.yaml#/components/schemas/Waardetabel'
            inOnderzoek:
              $ref: '#/components/schemas/NaamPersoonInOnderzoek'
    NaamPersoonInOnderzoek:
      allOf:
        - $ref: 'naam-beperkt-v1.yaml#/components/schemas/NaamPersoonInOnderzoekBeperkt'
        - type: object
          properties:
            aanduidingNaamgebruik:
              type: boolean
