openapi: 3.1.0
info:
  title: naam beperkt
  version: 1.0.0
  contact: {}
components:
  schemas:
    NaamPersoonBeperkt:
      description: |
        Gegevens over de naam van de persoon.
      allOf:
        - $ref: 'naam-basis-v1.yaml#/components/schemas/NaamBasis'
        - properties:
            volledigeNaam:
              $ref: '../../brp-api/naam/volledige-naam-v1.yaml#/components/schemas/VolledigeNaam'
            inOnderzoek:
              $ref: '#/components/schemas/NaamPersoonInOnderzoekBeperkt'
    NaamPersoonInOnderzoekBeperkt:
      allOf:
        - $ref: 'naam-basis-v1.yaml#/components/schemas/NaamBasisInOnderzoek'
        - type: object
          properties:
            volledigeNaam:
              type: boolean
