openapi: 3.1.0
info:
  title: Foutbericht
  description: |
    Definitie voor Foutbericht, een JSON representatie in lijn met [RFC7807](https://tools.ietf.org/html/rfc7807).
  version: 1.0.0
components:
  schemas:
    Foutbericht:
      type: object
      description: Terugmelding bij een fout. JSON representatie in lijn met [RFC7807](https://tools.ietf.org/html/rfc7807).
      properties:
        type:
          type: string
          format: uri
          description: Link naar meer informatie over deze fout
        title:
          description: Beschrijving van de fout
          $ref: '../tekst/tekst-80-diakriet-v1.yaml#/components/schemas/TekstMetDiakrieten80Lang'
        status:
          type: integer
          minimum: 100
          maximum: 600
          description: Http status code
        detail:
          description: Details over de fout
          $ref: '../tekst/tekst-200-diakriet-incl-haak-leestekens-v1.yaml#/components/schemas/TekstMetDiakrietenEnHaakLeestekens200Lang'
        instance:
          type: string
          format: uri
          description: Uri van de aanroep die de fout heeft veroorzaakt
        code:
          type: string
          description: Systeemcode die het type fout aangeeft
          $ref: '../tekst/tekst-25-v1.yaml#/components/schemas/Tekst25Lang'
