openapi: 3.1.0
info:
  title: Foutbericht
  description: |
    Definitie voor Foutbericht, een JSON representatie in lijn met [RFC7807](https://tools.ietf.org/html/rfc7807).
  version: 1.0.0
  contact: {}
components:
  schemas:
    Foutbericht:
      type: object
      description: Terugmelding bij een fout. JSON representatie in lijn met [RFC7807](https://tools.ietf.org/html/rfc7807).
      properties:
        type:
          type: string
          format: uri
          description: Link naar meer informatie over deze fout
        title:
          type: string
          pattern: ^[a-zA-Z0-9À-ž \.\-]{1,80}$
          description: Beschrijving van de fout
        status:
          type: integer
          minimum: 100
          maximum: 600
          description: Http status code
        detail:
          type: string
          pattern: ^[a-zA-Z0-9À-ž \.\-\(\)\,]{1,200}$
          description: Details over de fout
        instance:
          type: string
          format: uri
          description: Uri van de aanroep die de fout heeft veroorzaakt
        code:
          type: string
          pattern: ^[a-zA-Z0-9]{1,25}$
          description: Systeemcode die het type fout aangeeft
          minLength: 1
