openapi: 3.1.0
info:
  title: InvalidParams
  description: |
    Definitie voor InvalidParams, voor het leveren van details over fouten in een opgegeven parameter
  version: 1.0.0
  contact: {}
components:
  schemas:
    InvalidParams:
      type: object
      description: Details over fouten in opgegeven parameters
      properties:
        type:
          type: string
          format: uri
          example: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.5.1
        name:
          type: string
          pattern: ^[a-zA-Z0-9\.,_]{1,30}$
          description: Naam van de parameter
          example: "huisnummer"
        code:
          type: string
          pattern: ^[a-zA-Z0-9\.,_]{1,25}$
          description: Systeemcode die het type fout aangeeft
          minLength: 1
          example: "integer"
        reason:
          type: string
          pattern: ^[a-zA-Z0-9\.,_ ]{1,80}$
          description: Beschrijving van de fout op de parameterwaarde
          example: Waarde is geen geldig getal.
