openapi: 3.1.0
info:
  title: geboorte beperkt definitie
  version: 1.0.0
components:
  schemas:
    GeboorteBeperkt:
      type: object
      properties:
        datum:
          $ref: '../datum-v1.yaml#/components/schemas/GbaDatum'
