openapi: 3.1.0
info: 
  title: partner
  version: 1.0.0
components: 
  schemas:
    Partner:
      allOf: 
        - $ref: 'partner-basis-v1.yaml#/components/schemas/PartnerBasis'
        - type: object
          properties:
            datumIngangFamilierechtelijkeBetrekking:
              description: |
                De datum waarop de familierechtelijke betrekking is ontstaan.
              $ref: '../datum-v1.yaml#/components/schemas/GbaDatum'
            naam:
              $ref: '../naam/naam-basis-v1.yaml#/components/schemas/NaamBasis'
            geboorte:
              $ref: '../geboorte/geboorte-v1.yaml#/components/schemas/Geboorte'
            aangaanHuwelijkPartnerschap:
              $ref: 'aangaan-huwelijk-partnerschap-v1.yaml#/components/schemas/AangaanHuwelijkPartnerschap'
            ontbindingHuwelijkPartnerschap:
              $ref: "ontbinding-huwelijk-partnerschap-v1.yaml#/components/schemas/OntbindingHuwelijkPartnerschap"
            inOnderzoek:
              $ref: '../in-onderzoek-v1.yaml#/components/schemas/GbaInOnderzoek'
