openapi: 3.1.0
info:
  title: Maximaal 200 karakters lang tekst inclusief diakrieten en de (spatie).-(), leestekens
  description: |
    Definitie voor tekst bestaande uit minimaal 1 en maximaal 80 karakters. De karakters kunnen zijn:
      - kleine letters (a-z)
      - hoofdletters (A-Z)
      - cijfers (0-9)
      - diakrieten (À-ž)
      - spatie ( ), punt (.), min (-), ronde haakjes (()) en komma (,) leestekens
  version: 1.0.0
  contact: {}
components:
  schemas:
    TekstMetDiakrietenEnHaakLeestekens200Lang:
      type: string
      pattern: ^[a-zA-Z0-9À-ž \.\-\(\),]{1,200}$
