openapi: 3.1.0
info:
  title: Maximaal 25 karakters lang tekst
  description: |
    Definitie voor tekst bestaande uit minimaal 1 en maximaal 25 karakters. De karakters kunnen zijn:
      - kleine letters (a-z)
      - hoofdletters (A-Z)
      - cijfers (0-9)
  version: 1.0.0
  contact: {}
components:
  schemas:
    Tekst25Lang:
      type: string
      pattern: ^[a-zA-Z0-9]{1,25}$
