name: Valideer functionele specs en publiceer validatie summary in workflow job summary
description: |
  Valideer de functionele requirements gespecificeerd in Gherkin feature bestanden door het uitvoeren van ./scripts/specs-verify.sh.
  Genereer een summary van de validatie door het uitvoeren van ./scripts/generate-step-summary.js.
  Publiceer de summary in de worfklow job summary.

runs:
  using: composite
  steps:
    - name: Valideer functionele specs
      run: ./scripts/specs-verify.sh
      shell: bash

    - name: Genereer en publiceer validatie summary in de worfklow job summary
      if: ${{ !cancelled() }}
      run: |
          echo "### Cucumber Test Reports" >> $GITHUB_STEP_SUMMARY
          node ./scripts/generate-step-summary.js
          cat ./test-reports/cucumber-js/step-summary.txt >> $GITHUB_STEP_SUMMARY
      shell: bash

    - name: Publiceer test rapportage
      if: ${{ !cancelled() }}
      uses: dorny/test-reporter@v2
      with:
        name: Cucumber JS Test Reports
        report-title: Cucumber Test Reports
        path: ./test-reports/cucumber-js/**/*.xml
        reporter: java-junit
        only-summary: true