openapi: 3.1.0
info:
  title: persoon
  version: 1.0.0
  contact: {}
components:
  schemas:
    Persoon:
      allOf: 
        - $ref: 'persoon-basis-v1.yaml#/components/schemas/PersoonBasis'
        - type: object
          properties:
            aNummer:
              $ref: '../identificatienummers/anummer-v1.yaml#/components/schemas/ANummer'
            datumEersteInschrijvingGBA:
              $ref: '../datum-v1.yaml#/components/schemas/GbaDatum'
            gezagInOnderzoek:
              $ref: '../in-onderzoek-v1.yaml#/components/schemas/GbaInOnderzoek'
            uitsluitingKiesrecht:
              $ref: '../kiesrecht/uitsluiting-kiesrecht-v1.yaml#/components/schemas/GbaUitsluitingKiesrecht'
            europeesKiesrecht:
              $ref: '../kiesrecht/europees-kiesrecht-v1.yaml#/components/schemas/GbaEuropeesKiesrecht'
            naam:
              $ref: '../naam/naam-v1.yaml#/components/schemas/NaamPersoon'
            nationaliteiten:
              type: array
              items:
                $ref: '../nationaliteit-v1.yaml#/components/schemas/GbaNationaliteit'
            geboorte:
              $ref: '../geboorte/geboorte-v1.yaml#/components/schemas/Geboorte'
            overlijden:
              $ref: '../overlijden/overlijden-v1.yaml#/components/schemas/Overlijden'
            verblijfplaats:
              $ref: '../verblijfplaats/verblijfplaats-v1.yaml#/components/schemas/GbaVerblijfplaats'
            immigratie:
              $ref: '../immigratie/immigratie-v1.yaml#/components/schemas/Immigratie'
            datumInschrijvingInGemeente:
              $ref: '../datum-v1.yaml#/components/schemas/GbaDatum'
            indicatieCurateleRegister:
              $ref: '../indicatie-curatele-register-v1.yaml#/components/schemas/IndicatieCurateleRegister'
            indicatieGezagMinderjarige:
              $ref: '../waardetabel-v1.yaml#/components/schemas/Waardetabel'
              deprecated: true
            gezag:
              $ref: '../../brp-api/gezag/gezag-v1.yaml#/components/schemas/Gezag'
            verblijfstitel:
              $ref: '../verblijfstitel-v1.yaml#/components/schemas/GbaVerblijfstitel'
            kinderen:
              type: array
              items:
                $ref: '../../brp/kind-v1.yaml#/components/schemas/GbaKind'
            ouders:
              type: array
              items:
                $ref: '../../brp/ouder-v1.yaml#/components/schemas/GbaOuder'
            partners:
              type: array
              items:
                $ref: '../../brp/partner/partner-v1.yaml#/components/schemas/Partner'
