openapi: 3.1.0
info:
  title: verblijfplaats voorkomen (polymorf)
  version: 1.0.0
  contact: {}
components:
  schemas:
    AbstractVerblijfplaatsVoorkomen:
      type: object
      description: |
        Gegevens over het voorkomen van een verblijf of woonlocatie van een persoon.
      required:
        - type
      properties:
        type:
          type: string
      discriminator:
        propertyName: type
        mapping:
          Adres: 'adres-voorkomen-v1.yaml#/components/schemas/AdresVoorkomen'
          Locatie: 'locatie-voorkomen-v1.yaml#/components/schemas/LocatieVoorkomen'
          VerblijfplaatsBuitenland: 'verblijfplaats-buitenland-voorkomen-v1.yaml#/components/schemas/VerblijfplaatsBuitenlandVoorkomen'
          VerblijfplaatsOnbekend: 'verblijfplaats-onbekend-voorkomen-v1.yaml#/components/schemas/VerblijfplaatsOnbekendVoorkomen'
