openapi: 3.1.0
info: 
  title: nationaliteit onbekend
  version: 1.0.0
  contact: {}
components: 
  schemas:
    NationaliteitOnbekend:
      allOf:
        - $ref: 'nationaliteit-polymorf-v1.yaml#/components/schemas/AbstractNationaliteit'
        - type: object
          properties:
            inOnderzoek:
              $ref: 'nationaliteit-polymorf-v1.yaml#/components/schemas/NationaliteitInOnderzoek'
