openapi: 3.1.0
info: 
  title: vastgesteld niet nederlander
  version: 1.0.0
  contact: {}
components: 
  schemas:
    VastgesteldNietNederlander:
      allOf:
        - $ref: 'nationaliteit-polymorf-v1.yaml#/components/schemas/AbstractNationaliteit'
        - type: object
          properties:
            datumIngangGeldigheid:
              $ref: '../../brp-api/datum-polymorf-v1.yaml#/components/schemas/AbstractDatum'
            inOnderzoek:
              $ref: 'nationaliteit-polymorf-v1.yaml#/components/schemas/NationaliteitInOnderzoek'
